In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('FOREST FIRE.csv')

In [3]:
data

,Unnamed: 0,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,0,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,1,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire
2,2,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,3,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire
4,4,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...
238,239,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,fire
239,240,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,not fire
240,241,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
241,242,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
242,243,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [4]:
del data['Unnamed: 0']

In [5]:
data.isnull().sum()

Temperature    0
RH             0
Ws             0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
dtype: int64

In [6]:
data.duplicated().sum()

0

In [8]:
data['Classes'].value_counts()

fire        137
not fire    106
Name: Classes, dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  243 non-null    int64
 1   RH           243 non-null    int64
 2   Ws           243 non-null    int64
 3   Rain         243 non-null    float64
 4   FFMC         243 non-null    float64
 5   DMC          243 non-null    float64
 6   DC           243 non-null    float64
 7   ISI          243 non-null    float64
 8   BUI          243 non-null    float64
 9   FWI          243 non-null    float64
 10  Classes      243 non-null    object
dtypes: float64(7), int64(3), object(1)
memory usage: 21.0+ KB

In [10]:
data.columns

Index(['Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI', 'Classes'],
      dtype='object')

In [11]:
np.sort(data['RH'].unique())

array([21, 24, 26, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 86, 87, 88, 89, 90], dtype=int64)

In [12]:
print('The Minimum temperature is : ',min(data['Temperature'].unique()))
print('The Maximum temperature is : ',max(data['Temperature'].unique()))

The Minimum temperature is :  22
The Maximum temperature is :  42

In [14]:
data['Rain'].nunique()

39

In [20]:
pd.options.display.max_columns=500
pd.crosstab(data['Classes'],data['BUI'])

BUI,1.1,1.4,1.6,1.7,1.8,2.2,2.4,2.6,2.7,2.8,2.9,3.0,3.3,3.4,3.5,3.7,3.8,3.9,4.0,4.1,4.2,4.4,4.6,4.7,4.8,5.1,5.3,5.5,5.6,5.7,5.8,5.9,6.0,6.1,6.2,6.4,6.5,6.6,6.7,6.8,6.9,7.0,7.1,7.3,7.4,7.7,7.8,8.1,8.2,8.3,8.4,9.0,9.1,9.2,9.3,9.4,9.6,9.7,9.9,10.0,10.3,10.5,10.6,10.7,10.9,11.0,11.1,11.3,11.4,11.5,11.7,11.8,11.9,12.1,12.4,12.5,12.6,12.7,12.9,13.1,13.5,13.7,14.1,14.2,14.3,14.7,14.9,15.4,15.7,15.8,16.0,16.4,16.5,16.7,16.9,17.2,17.5,17.6,17.7,17.8,17.9,18.0,18.2,18.3,18.4,18.5,18.7,19.0,19.2,19.5,20.7,20.8,20.9,21.2,21.6,21.7,21.9,22.0,22.3,22.4,22.9,23.5,23.8,23.9,24.2,24.4,25.5,25.8,26.2,27.1,27.2,27.5,27.7,28.2,28.3,28.9,29.4,29.7,30.4,30.6,31.3,32.1,32.4,32.6,34.7,35.0,35.5,35.7,35.9,36.0,37.4,38.1,38.8,39.3,39.5,41.2,41.3,43.1,44.0,45.5,46.5,47.5,50.2,50.9,54.7,54.9,57.1,59.3,59.5,62.9,64.0,67.4,68.0
Classes,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
fire,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,1,1,2,0,1,2,2,0,1,1,0,0,1,1,1,0,1,1,2,1,1,1,0,2,0,0,0,0,1,2,0,1,0,1,1,1,1,3,1,0,1,1,1,2,1,2,1,1,2,1,1,1,2,2,1,1,1,1,1,1,1,1,2,1,0,1,1,1,1,0,1,1,1,3,2,1,1,2,1,1,1,1,1,1,1,1,1,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
not fire,1,2,2,2,2,1,3,2,2,2,3,5,1,2,1,2,1,3,1,1,2,3,1,1,1,3,1,2,2,1,2,1,1,1,2,0,1,1,2,2,1,0,1,1,1,2,0,1,0,3,1,0,0,1,0,0,1,1,0,0,0,2,0,1,1,0,0,0,1,1,1,1,1,1,0,0,1,0,1,0,0,0,2,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,2,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Classes  ']=le.fit_transform(data['Classes']).astype(int)

In [22]:
data

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Classes
0,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,1
1,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire,1
2,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,1
3,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,1
4,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,1
...,...,...,...,...,...,...,...,...,...,...,...,...
238,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,fire,0
239,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,not fire,1
240,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire,1
241,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire,1
242,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire,1

In [25]:
data.corr()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
Temperature,1.000000,-0.651400,-0.284510,-0.326492,0.676568,0.485687,0.376284,0.603871,0.459789,0.566670,-0.516015
RH,-0.651400,1.000000,0.244048,0.222356,-0.644873,-0.408519,-0.226941,-0.686667,-0.353841,-0.580957,0.432161
Ws,-0.284510,0.244048,1.000000,0.171506,-0.166548,-0.000721,0.079135,0.008532,0.031438,0.032368,0.069964
Rain,-0.326492,0.222356,0.171506,1.000000,-0.543906,-0.288773,-0.298023,-0.347484,-0.299852,-0.324422,0.379097
FFMC,0.676568,-0.644873,-0.166548,-0.543906,1.000000,0.603608,0.507397,0.740007,0.592011,0.691132,-0.769492
DMC,0.485687,-0.408519,-0.000721,-0.288773,0.603608,1.000000,0.875925,0.680454,0.982248,0.875864,-0.585658
DC,0.376284,-0.226941,0.079135,-0.298023,0.507397,0.875925,1.000000,0.508643,0.941988,0.739521,-0.511123
ISI,0.603871,-0.686667,0.008532,-0.347484,0.740007,0.680454,0.508643,1.000000,0.644093,0.922895,-0.735197
BUI,0.459789,-0.353841,0.031438,-0.299852,0.592011,0.982248,0.941988,0.644093,1.000000,0.857973,-0.586639
FWI,0.566670,-0.580957,0.032368,-0.324422,0.691132,0.875864,0.739521,0.922895,0.857973,1.000000,-0.719216
Classes,-0.516015,0.432161,0.069964,0.379097,-0.769492,-0.585658,-0.511123,-0.735197,-0.586639,-0.719216,1.000000